# Change these first
owner: George-Miao # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://miao.dev
  - name: Bitwarden
    url: https://bw.miao.dev
  - name: Pop.tg Site
    url: https://www.pop.tg
  - name: Pop.tg API
    url: https://pop.tg/api/v2/get_record
    method: POST
    body: '{ "key": "bili" }'
    expectedStatusCodes:
      - 200
      - 400
  - name: Typings.dev
    url: https://typings.dev
  - name: Rushia Button
    url: https://rushia.moe
  - name: RSS generator
    url: https://rss.miao.dev/bili/article/123
    expectedStatusCodes:
      - 404
  - name: Golden Axe
    url: https://golden-axe.fly.dev/health
    expectedStatusCodes:
      - 204
  - name: Grafana
    url: https://grafana.miao.dev/api/health
    expectedStatusCodes:
      - 200
  - name: FreshRSS
    url: https://freshrss.miao.dev
  - name: Headscale
    url: https://headscale.miao.dev/admin
assignees:
  - George-Miao

status-website:
  cname: status.miao.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of services made by George Miao"
  introMessage: Status website shows **real-time** data. By [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: George-Miao
